In [81]:
import numpy as np

In [4]:
lst = range(10)

In [6]:
array = np.array(lst)

In [8]:
array**.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
array.shape

(10,)

In [12]:
a1d = np.array(lst)

In [14]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a1d.shape

(10,)

In [18]:
num_lst = range(100000)

In [20]:
def square(lst):
    """
    Takes a collection of numbers and returns squares of each value
    """
    
    result = []
    
    for num in lst:
        if type(num) == str:
            return "Value must be number"
        result.append(num**2)

    return result

In [22]:
%timeit square(num_lst)

22.3 ms ± 3.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
num_arr = np.arange(100000)

In [ ]:
%timeit num_arr **2

In [49]:
type_casted_arr = np.array(range(1,4))

In [61]:
type_casted_arr.shape

(3,)

In [63]:
type_casted_arr.size

3

In [75]:
type_casted_arr.ndim

1

In [65]:
type_casted_arr.dtype

dtype('int32')

In [71]:
float_arr = np.array((1.2,))

dtype('float64')

In [103]:
arr = np.arange(1, 19).reshape(3,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [105]:
arr.shape

(3, 2, 3)

In [107]:
arr.ndim

3

In [113]:
arr = arr.reshape(2,1,9)

In [115]:
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18]]])