In [2]:
import numpy as np

In [10]:
lst = range(10)

In [12]:
array = np.array(lst)

In [14]:
array**.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
array.shape

(10,)

In [18]:
a1d = np.array(lst)

In [20]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1d.shape

(10,)

In [24]:
num_lst = range(100000)

In [26]:
def square(lst):
    """
    Takes a collection of numbers and returns squares of each value
    """
    
    result = []
    
    for num in lst:
        if type(num) == str:
            return "Value must be number"
        result.append(num**2)

    return result

In [28]:
%timeit square(num_lst)

26.2 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
num_arr = np.arange(100000)

In [30]:
%timeit num_arr **2

89.4 μs ± 4.47 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [31]:
type_casted_arr = np.array(range(1,4))

In [32]:
type_casted_arr.shape

(3,)

In [33]:
type_casted_arr.size

3

In [34]:
type_casted_arr.ndim

1

In [35]:
type_casted_arr.dtype

dtype('int32')

In [36]:
float_arr = np.array((1.2,))

In [39]:
arr = np.arange(1, 19).reshape(3,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [40]:
arr.shape

(3, 2, 3)

In [41]:
arr.ndim

3

In [42]:
arr = arr.reshape(2,1,9)

In [43]:
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18]]])

In [44]:
arr2d = np.arange(64).reshape(8,8)

In [45]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [46]:
arr2d[::-1,4:5]

array([[60],
       [52],
       [44],
       [36],
       [28],
       [20],
       [12],
       [ 4]])

In [47]:
arr = np.array([1,2])

In [48]:
arr[[True, False]]

array([1])

In [49]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [50]:
arr2d.reshape(2,4,8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [51]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [82]:
arr2d[2:3,2:4].shape

(1, 2)

In [86]:
arr3d = np.arange(30).reshape(2,3,5)

In [126]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [138]:
arr3d[0:1,1:2,2:3]

array([[[7]]])

In [106]:
from PIL import Image

In [108]:
img = Image.open("stc-image.jpg")

In [114]:
np_img_arr = np.asarray(img)

In [116]:
np_img_arr

array([[[141, 136, 130],
        [145, 140, 134],
        [148, 143, 137],
        ...,
        [225, 213, 199],
        [224, 212, 198],
        [223, 211, 197]],

       [[153, 148, 142],
        [155, 150, 144],
        [156, 151, 145],
        ...,
        [224, 212, 198],
        [223, 211, 197],
        [222, 210, 196]],

       [[152, 147, 141],
        [152, 147, 141],
        [152, 147, 141],
        ...,
        [224, 212, 198],
        [222, 210, 196],
        [221, 209, 195]],

       ...,

       [[144, 123, 104],
        [150, 129, 110],
        [149, 128, 109],
        ...,
        [157, 139, 125],
        [152, 134, 120],
        [149, 131, 119]],

       [[140, 119, 100],
        [152, 131, 112],
        [149, 128, 109],
        ...,
        [155, 139, 124],
        [149, 133, 118],
        [144, 128, 115]],

       [[141, 120,  99],
        [155, 134, 113],
        [150, 129, 108],
        ...,
        [151, 135, 120],
        [145, 129, 116],
        [139, 123, 110]]

In [122]:
np_img_arr[1:2,1:2,1:2] = 114

ValueError: assignment destination is read-only

In [124]:
img_arr = Image.fromarray(np_img_arr)

In [120]:
img_arr.save("asf.jpg")

In [20]:
from playsound import playsound

In [52]:
playsound("audio_file.mp3")


    Error 263 for command:
        close audio_file.mp3
    The specified device is not open or is not recognized by MCI.
Failed to close the file: audio_file.mp3


In [101]:
from pydub import AudioSegment

In [111]:
audio = AudioSegment.from_mp3("./audio_file.mp3")

FileNotFoundError: [WinError 2] The system cannot find the file specified